import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Nav } from "./components/layout/Navbar";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-body">
        <Nav />
        <div className="w-full flex justify-center">
          <div className="lg:max-w-[1440px]  w-full flex-col flex justify-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
